FROM mysql:8

MAINTAINER cola

# 만약 커스텀하게 설정하고 싶은 설정이 있다면 아래 파일을 만들어야 합니다.
ADD ./configs/my.cnf /etc/mysql/my.cnf

# seed 데이터
ADD ./seeds /seeds

# debian 한글설정
# https://hanryang1125.tistory.com/34
RUN apt-get update && apt-get install -y locales git && \
    localedef -f UTF-8 -i ko_KR ko_KR.UTF-8

ENV LANG=ko_KR.UTF-8 \
    LANGUAGE=ko_KR.UTF-8 \
    LC_ALL=ko_KR.UTF-8 \
    PYTHONIOENCODING=utf-8


EXPOSE 4406

#
CMD ["mysqld"]
