CREATE DATABASE IF NOT EXISTS example;

CREATE TABLE example.user(
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR (100),
  age INT
);

CREATE USER 'slave'@'%';
GRANT REPLICATION SLAVE ON *.* TO 'slave'@'%';

FLUSH PRIVILEGES;
